[theme]
base                   = "light"
backgroundColor        = "#F7F5F0"
secondaryBackgroundColor = "#FFFFFF"
textColor              = "#111111"
primaryColor           = "#1d375d"
font                   = "sans serif"
